# Publishes the npm package when a github relase is created

name: Node.js Package

on:
    release:
        types: [created]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/astro-feather-icons
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm run check
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
